<<<<<<< HEAD
<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Documentation</name>
   <tag></tag>
   <elementGuidId>7aefce90-5b9b-4098-bfa7-5e0ae5b4b650</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/section/header/header/div/div/nav/a[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5b3ed355-8b6d-4645-ab20-fc3403c0056c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>transition-all dark:hover:text-primary-200 relative after:w-0 hover:after:w-full after:h-0.5 after:bg-white after:absolute after:left-0 after:-bottom-1 after:transition-all</value>
      <webElementGuid>872db3ff-fbf1-4509-8a2e-502574e391ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://docs.accio.technology</value>
      <webElementGuid>38c38936-27b3-49ea-8fcb-79d7f7d256ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Documentation</value>
      <webElementGuid>b01bd43e-918b-48c4-abec-4ec6da5aabd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;app&quot;]/section[@class=&quot;min-h-0 bg-neutral-100 lg:flex lg:flex-col&quot;]/header[@class=&quot;z-50 top-0 left-0 w-full fixed w-full&quot;]/header[@class=&quot;py-3 2xl:py-5 transition-all z-50 undefined bg-transparent text-white dark:text-white dark:bg-neutral-900&quot;]/div[@class=&quot;px-5 mx-auto container flex items-center justify-between&quot;]/div[@class=&quot;flex gap-10 items-center&quot;]/nav[@class=&quot;hidden md:flex gap-10 items-center&quot;]/a[@class=&quot;transition-all dark:hover:text-primary-200 relative after:w-0 hover:after:w-full after:h-0.5 after:bg-white after:absolute after:left-0 after:-bottom-1 after:transition-all&quot;]</value>
      <webElementGuid>5dbf466e-91fc-4354-aff3-8e6d6a61b332</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section/header/header/div/div/nav/a[5]</value>
      <webElementGuid>7a8fd40d-9afc-4433-bcac-0a4d4fbf43e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Documentation')]</value>
      <webElementGuid>e1126eed-e630-4b87-8902-b18bcc5f1658</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='News'])[1]/following::a[1]</value>
      <webElementGuid>c78dd943-4424-4165-8df2-c37ba4988eae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pricing'])[1]/following::a[2]</value>
      <webElementGuid>f044be28-3d4f-4c8c-abab-5072251b9f1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign In to Console'])[1]/preceding::a[1]</value>
      <webElementGuid>26ef192f-a538-463b-a7c5-d619aa9bfdf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='en'])[1]/preceding::a[1]</value>
      <webElementGuid>a243a4ec-de90-4261-a1dd-3e5d7e37824b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Documentation']/parent::*</value>
      <webElementGuid>de884513-fdc8-4525-ae93-ab142bb607ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://docs.accio.technology')]</value>
      <webElementGuid>057d6f54-05bc-464c-a2c5-af25149a1985</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[5]</value>
      <webElementGuid>113f2b38-5fc3-4574-96c6-23e41c684849</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://docs.accio.technology' and (text() = 'Documentation' or . = 'Documentation')]</value>
      <webElementGuid>832840aa-1fc0-4278-b030-90ea41ba93b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
=======
<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Documentation</name>
   <tag></tag>
   <elementGuidId>7aefce90-5b9b-4098-bfa7-5e0ae5b4b650</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/section/header/header/div/div/nav/a[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5b3ed355-8b6d-4645-ab20-fc3403c0056c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>transition-all dark:hover:text-primary-200 relative after:w-0 hover:after:w-full after:h-0.5 after:bg-white after:absolute after:left-0 after:-bottom-1 after:transition-all</value>
      <webElementGuid>872db3ff-fbf1-4509-8a2e-502574e391ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://docs.accio.technology</value>
      <webElementGuid>38c38936-27b3-49ea-8fcb-79d7f7d256ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Documentation</value>
      <webElementGuid>b01bd43e-918b-48c4-abec-4ec6da5aabd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;app&quot;]/section[@class=&quot;min-h-0 bg-neutral-100 lg:flex lg:flex-col&quot;]/header[@class=&quot;z-50 top-0 left-0 w-full fixed w-full&quot;]/header[@class=&quot;py-3 2xl:py-5 transition-all z-50 undefined bg-transparent text-white dark:text-white dark:bg-neutral-900&quot;]/div[@class=&quot;px-5 mx-auto container flex items-center justify-between&quot;]/div[@class=&quot;flex gap-10 items-center&quot;]/nav[@class=&quot;hidden md:flex gap-10 items-center&quot;]/a[@class=&quot;transition-all dark:hover:text-primary-200 relative after:w-0 hover:after:w-full after:h-0.5 after:bg-white after:absolute after:left-0 after:-bottom-1 after:transition-all&quot;]</value>
      <webElementGuid>5dbf466e-91fc-4354-aff3-8e6d6a61b332</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section/header/header/div/div/nav/a[5]</value>
      <webElementGuid>7a8fd40d-9afc-4433-bcac-0a4d4fbf43e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Documentation')]</value>
      <webElementGuid>e1126eed-e630-4b87-8902-b18bcc5f1658</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='News'])[1]/following::a[1]</value>
      <webElementGuid>c78dd943-4424-4165-8df2-c37ba4988eae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pricing'])[1]/following::a[2]</value>
      <webElementGuid>f044be28-3d4f-4c8c-abab-5072251b9f1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign In to Console'])[1]/preceding::a[1]</value>
      <webElementGuid>26ef192f-a538-463b-a7c5-d619aa9bfdf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='en'])[1]/preceding::a[1]</value>
      <webElementGuid>a243a4ec-de90-4261-a1dd-3e5d7e37824b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Documentation']/parent::*</value>
      <webElementGuid>de884513-fdc8-4525-ae93-ab142bb607ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://docs.accio.technology')]</value>
      <webElementGuid>057d6f54-05bc-464c-a2c5-af25149a1985</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[5]</value>
      <webElementGuid>113f2b38-5fc3-4574-96c6-23e41c684849</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://docs.accio.technology' and (text() = 'Documentation' or . = 'Documentation')]</value>
      <webElementGuid>832840aa-1fc0-4278-b030-90ea41ba93b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
>>>>>>> 314f135d0807b642b2d0b92fa7654c87170c5bf7
