<<<<<<< HEAD
<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>News</name>
   <tag></tag>
   <elementGuidId>352b3a2c-27d8-4ace-9ea2-9d96344a41a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/section/header/header/div/div/nav/a[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cef6da30-f388-44fa-b200-48fe95b17e01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>transition-all dark:hover:text-primary-200 relative after:w-0 hover:after:w-full after:h-0.5 after:bg-white after:absolute after:left-0 after:-bottom-1 after:transition-all</value>
      <webElementGuid>767076ca-42f6-47c4-a477-58d5aa041d84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/news</value>
      <webElementGuid>b72fa8f0-e2e7-4a9b-a083-f301d81ae4dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>News</value>
      <webElementGuid>550f60bf-f201-4e99-a7e7-9d1732e13c18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;app&quot;]/section[@class=&quot;min-h-0 bg-neutral-100 lg:flex lg:flex-col&quot;]/header[@class=&quot;z-50 top-0 left-0 w-full fixed w-full&quot;]/header[@class=&quot;py-3 2xl:py-5 transition-all z-50 undefined bg-transparent text-white dark:text-white dark:bg-neutral-900&quot;]/div[@class=&quot;px-5 mx-auto container flex items-center justify-between&quot;]/div[@class=&quot;flex gap-10 items-center&quot;]/nav[@class=&quot;hidden md:flex gap-10 items-center&quot;]/a[@class=&quot;transition-all dark:hover:text-primary-200 relative after:w-0 hover:after:w-full after:h-0.5 after:bg-white after:absolute after:left-0 after:-bottom-1 after:transition-all&quot;]</value>
      <webElementGuid>81d6e278-df12-4fcc-b0e2-dabaee114daf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section/header/header/div/div/nav/a[4]</value>
      <webElementGuid>7ac3b8c6-8178-4781-b424-3b9dce3b729e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'News')]</value>
      <webElementGuid>084ee8dd-6afe-458e-991f-c6b3797c4747</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pricing'])[1]/following::a[1]</value>
      <webElementGuid>47a87349-991a-4d02-af47-e0f7b76ff4fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Features'])[1]/following::a[2]</value>
      <webElementGuid>3bd7953f-8983-45c5-a9d9-a073b8fcbc01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Documentation'])[1]/preceding::a[1]</value>
      <webElementGuid>10bb0782-85fe-4f74-904c-68a8f2c266f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign In to Console'])[1]/preceding::a[2]</value>
      <webElementGuid>e26a8ba2-c008-4b50-a3bb-4e45eff9fe02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='News']/parent::*</value>
      <webElementGuid>81f19e1f-0969-4c29-bb4c-6925f2a114ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/news')]</value>
      <webElementGuid>56ebc7fc-fed6-4b0e-b131-3fe81a8f309f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]</value>
      <webElementGuid>fd498fa0-22b9-4f27-8fb9-4cc3c3e9124a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/news' and (text() = 'News' or . = 'News')]</value>
      <webElementGuid>cf587b86-51a5-45de-8135-4a53e1b93cfe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
=======
<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>News</name>
   <tag></tag>
   <elementGuidId>352b3a2c-27d8-4ace-9ea2-9d96344a41a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/section/header/header/div/div/nav/a[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cef6da30-f388-44fa-b200-48fe95b17e01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>transition-all dark:hover:text-primary-200 relative after:w-0 hover:after:w-full after:h-0.5 after:bg-white after:absolute after:left-0 after:-bottom-1 after:transition-all</value>
      <webElementGuid>767076ca-42f6-47c4-a477-58d5aa041d84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/news</value>
      <webElementGuid>b72fa8f0-e2e7-4a9b-a083-f301d81ae4dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>News</value>
      <webElementGuid>550f60bf-f201-4e99-a7e7-9d1732e13c18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;app&quot;]/section[@class=&quot;min-h-0 bg-neutral-100 lg:flex lg:flex-col&quot;]/header[@class=&quot;z-50 top-0 left-0 w-full fixed w-full&quot;]/header[@class=&quot;py-3 2xl:py-5 transition-all z-50 undefined bg-transparent text-white dark:text-white dark:bg-neutral-900&quot;]/div[@class=&quot;px-5 mx-auto container flex items-center justify-between&quot;]/div[@class=&quot;flex gap-10 items-center&quot;]/nav[@class=&quot;hidden md:flex gap-10 items-center&quot;]/a[@class=&quot;transition-all dark:hover:text-primary-200 relative after:w-0 hover:after:w-full after:h-0.5 after:bg-white after:absolute after:left-0 after:-bottom-1 after:transition-all&quot;]</value>
      <webElementGuid>81d6e278-df12-4fcc-b0e2-dabaee114daf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section/header/header/div/div/nav/a[4]</value>
      <webElementGuid>7ac3b8c6-8178-4781-b424-3b9dce3b729e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'News')]</value>
      <webElementGuid>084ee8dd-6afe-458e-991f-c6b3797c4747</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pricing'])[1]/following::a[1]</value>
      <webElementGuid>47a87349-991a-4d02-af47-e0f7b76ff4fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Features'])[1]/following::a[2]</value>
      <webElementGuid>3bd7953f-8983-45c5-a9d9-a073b8fcbc01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Documentation'])[1]/preceding::a[1]</value>
      <webElementGuid>10bb0782-85fe-4f74-904c-68a8f2c266f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign In to Console'])[1]/preceding::a[2]</value>
      <webElementGuid>e26a8ba2-c008-4b50-a3bb-4e45eff9fe02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='News']/parent::*</value>
      <webElementGuid>81f19e1f-0969-4c29-bb4c-6925f2a114ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/news')]</value>
      <webElementGuid>56ebc7fc-fed6-4b0e-b131-3fe81a8f309f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]</value>
      <webElementGuid>fd498fa0-22b9-4f27-8fb9-4cc3c3e9124a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/news' and (text() = 'News' or . = 'News')]</value>
      <webElementGuid>cf587b86-51a5-45de-8135-4a53e1b93cfe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
>>>>>>> 314f135d0807b642b2d0b92fa7654c87170c5bf7
